### ISSUE TITLE
YouTube embed support could be better

### ISSUE THREAD

**Issue by epheterson** [msolters/Tiles#107]
Check it out on mine :
http://tilesjs.meteor.com/pheterson

The Steel Wool Fun video was embedded by just dropping the link into froala and it appears to embedded an iframe that's too tall to be useful in the preview area.

**Comment by epheterson** [comment]
I can't access the play/pause buttons and I see a lot of the black bar with the video.

**Comment by epheterson** [comment]
![screen shot 2015-07-19 at 10 24 36 am](https://cloud.githubusercontent.com/assets/151483/8766951/6fd98742-2e00-11e5-9f54-c86b095e75a4.png)

**Comment by msolters** [comment]
Yeah so there's two issues, max-width and height.  I've already actually forced children inside Tile previews like that to never be more than 100%.  It used to be the Youtube would go off to the right, as well as off the bottom.

Of course the only solution will be to make the entire video scale down to fit inside.  The the tricky thing is iFrames are really, really bitchy and insist on a fixed-width by design.  (remind you of anyone)  So I can fix it, but the videos will end up being quite small due to the iFrame insisting on an aspect ratio.  Not much I can do here except encourage the user to open the whole thing, or redesign our tiles to be a ratio youtube allows.
