### ISSUE TITLE
Clicking on tile should open big view

### ISSUE THREAD

**Issue by epheterson** [msolters/Tiles#15]
Currently, you have to click 'Read More'

Important that if user is clicking a link on the tile, that goes through instead of opening it up, only exception I can think of.

**Comment by msolters** [comment]
Yeah but with the current method the user is forced to click some very small text that is easily missed.  That's like, the very core of the Apple design aesthetic.  Otherwise we'd be running around with iPhones where you can select a link on the first tap instead of the 6th or 7th.  Are you sure you want to throw that all away?

**Comment by epheterson** [comment]
I tried to teach someone to use their windows phone today.

Could not figure out how to increase the screen brightness.

**Comment by epheterson** [comment]
Also she tapped the Facebook icon to get to her phone contacts. I was like wtf and left.

**Comment by msolters** [comment]
Same with iPhone and choosing a WiFi network.  Gotta go all the way to home screen, and then into settings, and then drill down to the networking settings.

**Comment by epheterson** [comment]
Yeah I have a bug on that with a good idea how to make it faster... fortunately we have Command Center  for most quick controls (ie. Wifi on/off and brightness)

**Comment by msolters** [comment]
Android Command Center lets you do all that from any screen, as well as jump to that particular setting's detail view.

SO IM CONSIDERING THIS ISSUE CLOSEDDDDD
